import { useState, useEffect } from 'react'
import './ImageCarousel.css'

function ImageCarousel() {
  const [currentImageIndex, setCurrentImageIndex] = useState(0)
  
  // List of images from public/img folder - Updated with new images
  const images = [
    '/img/@speciale_flag #digital #degital_marketing #youcandoit #stiki.jpeg',
    '/img/aecd12b64d84e81e04407915f4293d3d.jpg',
    '/img/Agadir 33_34, Rabon.jpeg',
    '/img/Ba 3aroub #naselghiwane photo generated by @simo_bob_ #stickers #threshold @dunia_batma @btissambatmaofficial.jpeg',
    '/img/Be positive.jpeg',
    '/img/by @vector_hamza _ 🇲🇦 wallpaper.jpeg',
    '/img/Cigogne (1).jpeg',
    '/img/Cigogne.jpeg',
    '/img/Flag Spécial.jpeg',
    '/img/L\'mâallem Van Gogh 😎😍.jpeg',
    '/img/Moroccan Art_Instagram_ @blizzart_ 🇲🇦.jpeg',
    '/img/Tableaux décoratifs au Maroc - Art Mural en Toile,Plexiglass by KOLORS.jpeg',
    '/img/Taxi pour l\'Atlas.jpeg',
    '/img/téléchargement (1).jpeg',
    '/img/téléchargement (10).jpeg',
    '/img/téléchargement (2).jpeg',
    '/img/téléchargement (3).jpeg',
    '/img/téléchargement (4).jpeg',
    '/img/téléchargement (5).jpeg',
    '/img/téléchargement (6).jpeg',
    '/img/téléchargement (7).jpeg',
    '/img/téléchargement (8).jpeg',
    '/img/téléchargement (9).jpeg',
    '/img/Un drapeau beau comme une rose.jpeg'
  ]

  // Auto-change image every 5 seconds
  useEffect(() => {
    if (images.length === 0) return
    const interval = setInterval(() => {
      setCurrentImageIndex((prev) => (prev + 1) % images.length)
    }, 5000)
    return () => clearInterval(interval)
  }, [images.length])

  const handlePrevImage = () => {
    setCurrentImageIndex((prev) => (prev - 1 + images.length) % images.length)
  }

  const handleNextImage = () => {
    setCurrentImageIndex((prev) => (prev + 1) % images.length)
  }

  const handleDotClick = (index) => {
    setCurrentImageIndex(index)
  }

  // Handle image load errors
  const handleImageError = (e) => {
    console.error('Image failed to load:', images[currentImageIndex])
    e.target.src = '/img/aecd12b64d84e81e04407915f4293d3d.jpg' // Fallback image
  }

  if (images.length === 0) {
    return (
      <div className="carousel-container">
        <p style={{ textAlign: 'center', color: 'var(--dark-brown)' }}>Aucune image disponible</p>
      </div>
    )
  }

  return (
    <div className="carousel-container">
      <div className="carousel-wrapper">
        <button className="carousel-btn carousel-btn-prev" onClick={handlePrevImage}>
          ←
        </button>

        <div className="carousel-images">
          <img
            key={currentImageIndex}
            src={images[currentImageIndex]}
            alt={`Slide ${currentImageIndex + 1}`}
            className="carousel-image"
            onError={handleImageError}
            loading="lazy"
          />
        </div>

        <button className="carousel-btn carousel-btn-next" onClick={handleNextImage}>
          →
        </button>
      </div>

      {/* Dots Navigation */}
      <div className="carousel-dots">
        {images.map((_, index) => (
          <button
            key={index}
            className={`dot ${index === currentImageIndex ? 'active' : ''}`}
            onClick={() => handleDotClick(index)}
            aria-label={`Go to slide ${index + 1}`}
          />
        ))}
      </div>

      {/* Image Counter */}
      <div className="carousel-counter">
        {currentImageIndex + 1} / {images.length}
      </div>
    </div>
  )
}

export default ImageCarousel
